for c in range(2, 50, 2):
    print(c, end=' ')
print('ACABOU!')
#O CÓDIGO FOI SIMPLIFICADO ASSIM EVITANDO UM MAIOR NÚMERO DE REPETIÇÕES
#COM O 'PASSO' 2 FOI POSSÍVEL RETIRAR O IF E REDUZIR O NÚMERO DE LOOPS